package com.sysnet.dbsb.ws.picc;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * PiccWebServiceInterfaceImplService service = new PiccWebServiceInterfaceImplService();
 * PiccWebServiceInterfaceImpl portType = service.getPiccWSInterface();
 * portType.transBusinessForPICCAsync(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "PiccWebServiceInterfaceImplService", targetNamespace = "http://127.0.0.1:8080/eapdomain/services/PiccWSInterface", wsdlLocation = "file:/E:/\u65b0\u519c\u5408/\u5927\u75c5/\u9633\u6cc9\u4eba\u4fdd/PiccWSInterface.wsdl")
public class PiccWebServiceInterfaceImplService extends Service {

	private final static URL PICCWEBSERVICEINTERFACEIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.sysnet.dbsb.ws.picc.PiccWebServiceInterfaceImplService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.sysnet.dbsb.ws.picc.PiccWebServiceInterfaceImplService.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"file:/E:/\u65b0\u519c\u5408/\u5927\u75c5/\u9633\u6cc9\u4eba\u4fdd/PiccWSInterface.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/E:/\u65b0\u519c\u5408/\u5927\u75c5/\u9633\u6cc9\u4eba\u4fdd/PiccWSInterface.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PICCWEBSERVICEINTERFACEIMPLSERVICE_WSDL_LOCATION = url;
	}

	public PiccWebServiceInterfaceImplService(URL wsdlLocation,
			QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PiccWebServiceInterfaceImplService() {
		super(PICCWEBSERVICEINTERFACEIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://127.0.0.1:8080/eapdomain/services/PiccWSInterface",
				"PiccWebServiceInterfaceImplService"));
	}

	public PiccWebServiceInterfaceImplService(URL wsdlLocation) {
		super(wsdlLocation, new QName(
				"http://127.0.0.1:8080/eapdomain/services/PiccWSInterface",
				"PiccWebServiceInterfaceImplService"));
	}

	/**
	 * 
	 * @return returns PiccWebServiceInterfaceImpl
	 */
	@WebEndpoint(name = "PiccWSInterface")
	public PiccWebServiceInterfaceImpl getPiccWSInterface() {
		return super.getPort(new QName(
				"http://127.0.0.1:8080/eapdomain/services/PiccWSInterface",
				"PiccWSInterface"), PiccWebServiceInterfaceImpl.class);
	}

}
