package com.sysnet.dbsb.ws.plicc;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WebServiceInterfaceService service = new WebServiceInterfaceService();
 * WebServiceInterface portType = service.getWebServiceInterfacePort();
 * portType.excute(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WebServiceInterfaceService", targetNamespace = "http://webservice.create.com/", wsdlLocation = "http://sx.cisex.clic:8080/cis/services/test?wsdl")
public class WebServiceInterfaceService extends Service {

	private final static URL WEBSERVICEINTERFACESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.sysnet.dbsb.ws.plicc.WebServiceInterfaceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.sysnet.dbsb.ws.plicc.WebServiceInterfaceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://74.0.160.3:8080/cis/services/test?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://sx.cisex.clic:8080/cis/services/test?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WEBSERVICEINTERFACESERVICE_WSDL_LOCATION = url;
	}

	public WebServiceInterfaceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WebServiceInterfaceService() {
		super(WEBSERVICEINTERFACESERVICE_WSDL_LOCATION, new QName(
				"http://webservice.create.com/", "WebServiceInterfaceService"));
	}
	
	public WebServiceInterfaceService(String url) throws MalformedURLException {
		super(new URL(url), new QName(
				"http://webservice.create.com/", "WebServiceInterfaceService"));
	}
	/**
	 * 
	 * @return returns WebServiceInterface
	 */
	@WebEndpoint(name = "WebServiceInterfacePort")
	public WebServiceInterface getWebServiceInterfacePort() {
		return super.getPort(new QName("http://webservice.create.com/",
				"WebServiceInterfacePort"), WebServiceInterface.class);
	}

}
