/**
* @Title: InsuredPersonServiceImplTest.java
* @Package com.sysnet.dbsb.service.impl
* @Description: 
* @author dengweihua
* @date 2016年1月21日 下午4:22:59
* @version V1.0
*/
package com.sysnet.dbsb.service.impl;

import javax.annotation.Resource;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.sysnet.dbsb.dao.DBMessageMapper;
import com.sysnet.dbsb.model.common.DBMessage;

/**
* @ClassName: InsuredPersonServiceImplTest
* @Description: 
* @author dengweihua
* @date 2016年1月21日 下午4:22:59
*/
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath:conf/applicationContext.xml", "classpath:conf/spring-mybatis.xml" })
public class DB_MessageMapperTest {
	@Resource
	DBMessageMapper dao;
	

	@Test
	public void testInsert() {
		 DBMessage message = new DBMessage();
		 message.setBUS_CODE("1111");
		 message.setBUS_SUB_CODE("2222");
		message.setID("999");
		String REQUEST=
				"<root>\n" +
						"    <head>\n" + 
						"        <standard_version_code>V2.4.2</standard_version_code>\n" + 
						"        <group_id>20160330165936</group_id>\n" + 
						"        <bus_code>100013</bus_code>\n" + 
						"        <bus_sub_code>01</bus_sub_code>\n" + 
						"        <bus_type>0</bus_type>\n" + 
						"        <total_count>1</total_count>\n" + 
						"        <total_packge>1</total_packge>\n" + 
						"        <package_id>1</package_id>\n" + 
						"        <data_count>1</data_count>\n" + 
						"        <area_code>610402</area_code>\n" + 
						"        <outside_system_code>SXXNH_SYSNET</outside_system_code>\n" + 
						"        <outside_system_type>2</outside_system_type>\n" + 
						"        <ding_hosp_code>56377729461110111C2201</ding_hosp_code>\n" + 
						"        <option_person_code>admin</option_person_code>\n" + 
						"        <insured_year>2016</insured_year>\n" + 
						"    </head>\n" + 
						"    <body>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"        <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    <hospitalCompensationInfo>\n" + 
						"            <medical_record_no>6104021042330010210</medical_record_no>\n" + 
						"            <hospital_registration_sn>61040219761230484X</hospital_registration_sn>\n" + 
						"            <name>张亚娟</name>\n" + 
						"            <sex>2</sex>\n" + 
						"            <id_type>I</id_type>\n" + 
						"            <id_number>61040219761230484X</id_number>\n" + 
						"            <settlement_number>415</settlement_number>\n" + 
						"            <in_hospital_style>2</in_hospital_style>\n" + 
						"            <leave_state>1</leave_state>\n" + 
						"            <referral_ratio>0.00</referral_ratio>\n" + 
						"            <leave_hospital_style>1</leave_hospital_style>\n" + 
						"            <leave_date>2016-03-01</leave_date>\n" + 
						"            <death_time></death_time>\n" + 
						"            <leave_disease_code>S22.001</leave_disease_code>\n" + 
						"            <complication></complication>\n" + 
						"            <total_payment>33830.67</total_payment>\n" + 
						"            <jialei_payment></jialei_payment>\n" + 
						"            <yilei_baoxiao></yilei_baoxiao>\n" + 
						"            <yilei_payment>0</yilei_payment>\n" + 
						"            <binglei_yibao>16119.6</binglei_yibao>\n" + 
						"            <binglei_payment>1522.24</binglei_payment>\n" + 
						"            <zy_payment></zy_payment>\n" + 
						"            <xy_payment></xy_payment>\n" + 
						"            <yb_start_pay_line>3000</yb_start_pay_line>\n" + 
						"            <fit_into_yb_amount>32308.43</fit_into_yb_amount>\n" + 
						"            <yb_compensation>16119.6</yb_compensation>\n" + 
						"            <yb_year_compensation></yb_year_compensation>\n" + 
						"            <third_party_compensation>0</third_party_compensation>\n" + 
						"            <year_third_party_compensation>0</year_third_party_compensation>\n" + 
						"            <db_compensation>4094.42</db_compensation>\n" + 
						"            <db_year_compensation>0</db_year_compensation>\n" + 
						"            <arg1></arg1>\n" + 
						"            <arg2></arg2>\n" + 
						"            <arg3></arg3>\n" + 
						"            <arg4></arg4>\n" + 
						"            <arg5></arg5>\n" + 
						"            <arg6></arg6>\n" + 
						"            <arg7></arg7>\n" + 
						"            <arg8></arg8>\n" + 
						"            <arg9></arg9>\n" + 
						"            <arg10></arg10>\n" + 
						"        </hospitalCompensationInfo>\n" + 
						"    </body>\n" + 
						"</root>";

		message.setREQUEST(REQUEST);
		dao.insert(message);
		
	}
}
